version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: backend-postgres
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
      POSTGRES_DB: backend
    ports:
      - "5555:5432"
    command: postgres -c 'max_connections=200'
